name: Code Contribution Appreciation

on:
  push:
    branches:
      - main

jobs:
  appreciate-contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Show Appreciation
        run: |
          echo "Thank you for your contribution! ðŸŒŸ"
